STICKER_001 = [
    "CAACAgIAAxkBAAEHRq9jxSeJhkf8i8Tp8ybRbdPs-1azogACcwMAAvnkbAABicHsqQgiHWstBA",
    "CAACAgIAAxkBAAEHRu1jxSuo6Bv1aoGqGsUv_qtP-Ey3WgAChwMAAvnkbAABiagOdmOPT-4tBA"
    "CAACAgIAAxkBAAEHRvFjxSu8OK99Gb_mQgMJltHTOG05bgACjwMAAvnkbAAB0W6ojo-UwigtBA"
    "CAACAgIAAxkBAAEHRvVjxSv-3xhuAAEWFW51aeuLw2-NXsUAAtcDAAL55GwAAa6TsoCsPeDLLQQ"
    "CAACAgIAAxkBAAEHRvdjxSwr0wXgJNrb2yjIL8u2L9RMLAACMQADhxAXOF6mFUC024l_LQQ"
]



    #"CAACAgIAAxkBAAEHRqdjxSd3XPH6GJf0ZDfXf_oAAclqKfgAAqYDAAL55GwAAX-gWGvz-gsNLQQ",
    # "CAACAgIAAxkBAAEHRhZjxSaF6yXkI9s0db7c4JC_uakubQACxQADVC5MImapj_vXyzY5LQQ",
    # "CAACAgIAAxkBAAEHRidjxSbP0sy5deHeJeimqlmhUDcyTAACxwADVC5MIgEy3LeuHozoLQQ",
    # "CAACAgIAAxkBAAEHRidjxSbP0sy5deHeJeimqlmhUDcyTAACxwADVC5MIgEy3LeuHozoLQQ",
    # "CAACAgIAAxkBAAEHRjdjxSbmuY4PWG6jkROue4W5jm_VNAACyAADVC5MIg3Dmwzh0lJdLQQ",
    # "CAACAgIAAxkBAAEHRjpjxSbobwABRvW6GX7RxvS5vW6wP3YAAskAA1QuTCJ_tutSgQsJQi0E",
    # "CAACAgIAAxkBAAEHRj5jxSbtAupBciyfgaoAAeO4WqsRE48AAsoAA1QuTCJi0gxr3nni5i0E",
    # "CAACAgIAAxkBAAEHRkFjxSbw-XPOOEiL0xVwT5xI4RZVZwACzgADVC5MIq3wL56Zr5HkLQQ",
    # "CAACAgIAAxkBAAEHRk1jxScB6ISi44w_OFZwuROzVZsb6QACTRgAAlP_UEuaUnlr9wuhTi0E",
